mv "svgexport-001.png" "Tocorsia Emblem Duchy of Pupunmaa.png"
mv "svgexport-002.png" "Tocorsia Emblem Grand Duchy of Baken.png"
mv "svgexport-003.png" "Tocorsia Emblem Republic of Lorumia.png"
mv "svgexport-004.png" "Tocorsia Emblem Jarpantan Theocracy.png"
mv "svgexport-005.png" "Tocorsia Emblem Turk Khaganate.png"
mv "svgexport-006.png" "Tocorsia Emblem United Provinces of Telyilia.png"
mv "svgexport-007.png" "Tocorsia Emblem Piniacian Despotate.png"
mv "svgexport-008.png" "Tocorsia Emblem Eschbrinian Theocracy.png"
mv "svgexport-009.png" "Tocorsia Emblem Diocese of Ildetia.png"
mv "svgexport-010.png" "Tocorsia Emblem Patriarchate of Gorgania.png"
mv "svgexport-011.png" "Tocorsia Emblem Kingdom of Rifsosia.png"
mv "svgexport-012.png" "Tocorsia Emblem Tsardom of Kapech.png"
mv "svgexport-013.png" "Tocorsia Emblem Aykutyurt Horde.png"
mv "svgexport-014.png" "Tocorsia Emblem Kingdom of Tydolisia.png"
mv "svgexport-015.png" "Tocorsia Emblem Duchy of Valkeama.png"
mv "svgexport-016.png" "Tocorsia Emblem Protectorate of Pseikon.png"
mv "svgexport-017.png" "Tocorsia Emblem Principality of Huecavia.png"
mv "svgexport-018.png" "Tocorsia Emblem Beylik of Vuzerlyurt.png"
mv "svgexport-019.png" "Tocorsia Emblem Silo County.png"
mv "svgexport-020.png" "Tocorsia Emblem Tameskog Landgrave.png"
mv "svgexport-021.png" "Tocorsia Emblem Silkes County.png"
mv "svgexport-022.png" "Tocorsia Emblem Flaksvog County.png"
mv "svgexport-023.png" "Tocorsia Emblem Bifla County.png"
mv "svgexport-024.png" "Tocorsia Emblem Laudalen Landgrave.png"
mv "svgexport-025.png" "Tocorsia Emblem Sugavik County.png"
mv "svgexport-026.png" "Tocorsia Emblem Grimstania Island.png"
mv "svgexport-027.png" "Tocorsia Emblem Nigripi Province.png"
mv "svgexport-028.png" "Tocorsia Emblem Theliuscum Province.png"
mv "svgexport-029.png" "Tocorsia Emblem Naiscavumia Department.png"
mv "svgexport-030.png" "Tocorsia Emblem Vinium Province.png"
mv "svgexport-031.png" "Tocorsia Emblem Dubriniumia Province.png"
mv "svgexport-032.png" "Tocorsia Emblem Bolina Province.png"
mv "svgexport-033.png" "Tocorsia Emblem Vicacalebu Province.png"
mv "svgexport-034.png" "Tocorsia Emblem Raususia Province.png"
mv "svgexport-035.png" "Tocorsia Emblem Parianisia Province.png"
mv "svgexport-036.png" "Tocorsia Emblem Jaszsolca Territory.png"
mv "svgexport-037.png" "Tocorsia Emblem Olmevil Territory.png"
mv "svgexport-038.png" "Tocorsia Emblem Zsampapia Land.png"
mv "svgexport-039.png" "Tocorsia Emblem Castesia Dependency.png"
mv "svgexport-040.png" "Tocorsia Emblem Tukvemia Parish.png"
mv "svgexport-041.png" "Tocorsia Emblem Bunsey Parish.png"
mv "svgexport-042.png" "Tocorsia Emblem Stanydon Parish.png"
mv "svgexport-043.png" "Tocorsia Emblem Vakia Parish.png"
mv "svgexport-044.png" "Tocorsia Emblem Hirvi Parish.png"
mv "svgexport-045.png" "Tocorsia Emblem Sidmin Parish.png"
mv "svgexport-046.png" "Tocorsia Emblem Hautiokia Parish.png"
mv "svgexport-047.png" "Tocorsia Emblem Kemimamo Parish.png"
mv "svgexport-048.png" "Tocorsia Emblem Vaiviesmaa Parish.png"
mv "svgexport-049.png" "Tocorsia Emblem Palvajmaa Parish.png"
mv "svgexport-050.png" "Tocorsia Emblem Kauma Parish.png"
mv "svgexport-051.png" "Tocorsia Emblem Epepesen Earldom.png"
mv "svgexport-052.png" "Tocorsia Emblem Bobakyurt Earldom.png"
mv "svgexport-053.png" "Tocorsia Emblem Rigninoia County.png"
mv "svgexport-054.png" "Tocorsia Emblem Algesyurt County.png"
mv "svgexport-055.png" "Tocorsia Emblem Kozozobaya County.png"
mv "svgexport-056.png" "Tocorsia Emblem Dolu County.png"
mv "svgexport-057.png" "Tocorsia Emblem Denekibi County.png"
mv "svgexport-058.png" "Tocorsia Emblem Castte County.png"
mv "svgexport-059.png" "Tocorsia Emblem Marma County.png"
mv "svgexport-060.png" "Tocorsia Emblem Erbe County.png"
mv "svgexport-061.png" "Tocorsia Emblem New Dolu Colony.png"
mv "svgexport-062.png" "Tocorsia Emblem Dezet Land.png"
mv "svgexport-063.png" "Tocorsia Emblem Tovetia Canton.png"
mv "svgexport-064.png" "Tocorsia Emblem Rzhia County.png"
mv "svgexport-065.png" "Tocorsia Emblem Subechia Canton.png"
mv "svgexport-066.png" "Tocorsia Emblem Lukia Canton.png"
mv "svgexport-067.png" "Tocorsia Emblem Cavia Canton.png"
mv "svgexport-068.png" "Tocorsia Emblem Vorod Canton.png"
mv "svgexport-069.png" "Tocorsia Emblem Tamesia County.png"
mv "svgexport-070.png" "Tocorsia Emblem Rzhia Canton.png"
mv "svgexport-071.png" "Tocorsia Emblem Louriveia County.png"
mv "svgexport-072.png" "Tocorsia Emblem Chechers Province.png"
mv "svgexport-073.png" "Tocorsia Emblem Koria Canton.png"
mv "svgexport-074.png" "Tocorsia Emblem Drutslavl County.png"
mv "svgexport-075.png" "Tocorsia Emblem Pylisia Barony.png"
mv "svgexport-076.png" "Tocorsia Emblem Naupia Barony.png"
mv "svgexport-077.png" "Tocorsia Emblem Kysosia Barony.png"
mv "svgexport-078.png" "Tocorsia Emblem Pholisia County.png"
mv "svgexport-079.png" "Tocorsia Emblem Poporionia Barony.png"
mv "svgexport-080.png" "Tocorsia Emblem Throlis County.png"
mv "svgexport-081.png" "Tocorsia Emblem Castigliaro Land.png"
mv "svgexport-082.png" "Tocorsia Emblem Durnach Parish.png"
mv "svgexport-083.png" "Tocorsia Emblem Frohn Parish.png"
mv "svgexport-084.png" "Tocorsia Emblem Donausach Parish.png"
mv "svgexport-085.png" "Tocorsia Emblem Buhlin Parish.png"
mv "svgexport-086.png" "Tocorsia Emblem Glat Parish.png"
mv "svgexport-087.png" "Tocorsia Emblem Fregengen Parish.png"
mv "svgexport-088.png" "Tocorsia Emblem Braunzelngen Parish.png"
mv "svgexport-089.png" "Tocorsia Emblem Kupenhia Parish.png"
mv "svgexport-090.png" "Tocorsia Emblem Wiesendorf Parish.png"
mv "svgexport-091.png" "Tocorsia Emblem Canta Parish.png"
mv "svgexport-092.png" "Tocorsia Emblem Openia Deanery.png"
mv "svgexport-093.png" "Tocorsia Emblem Teibach Parish.png"
mv "svgexport-094.png" "Tocorsia Emblem Iterken Parish.png"
mv "svgexport-095.png" "Tocorsia Emblem Buginland Island.png"
mv "svgexport-096.png" "Tocorsia Emblem Media Deanery.png"
mv "svgexport-097.png" "Tocorsia Emblem Cambelosia Deanery.png"
mv "svgexport-098.png" "Tocorsia Emblem Zaia Deanery.png"
mv "svgexport-099.png" "Tocorsia Emblem Meria Island.png"
mv "svgexport-100.png" "Tocorsia Emblem Gorgan Deanery.png"
mv "svgexport-101.png" "Tocorsia Emblem Celevigia Deanery.png"
mv "svgexport-102.png" "Tocorsia Emblem Giucania Deanery.png"
mv "svgexport-103.png" "Tocorsia Emblem Valvicerelvi Deanery.png"
mv "svgexport-104.png" "Tocorsia Emblem Tempia Deanery.png"
mv "svgexport-105.png" "Tocorsia Emblem Pyrmia Deanery.png"
mv "svgexport-106.png" "Tocorsia Emblem Grottero Deanery.png"
mv "svgexport-107.png" "Tocorsia Emblem Iarathory Parish.png"
mv "svgexport-108.png" "Tocorsia Emblem Farvianoro Deanery.png"
mv "svgexport-109.png" "Tocorsia Emblem Spervo Deanery.png"
mv "svgexport-110.png" "Tocorsia Emblem Wiganland Territory.png"
mv "svgexport-111.png" "Tocorsia Emblem Dipomisia Island.png"
mv "svgexport-112.png" "Tocorsia Emblem Sormelahia Margrave.png"
mv "svgexport-113.png" "Tocorsia Emblem Drarasland Barony.png"
mv "svgexport-114.png" "Tocorsia Emblem Capranolia Margrave.png"
mv "svgexport-115.png" "Tocorsia Emblem Sorneske Margrave.png"
mv "svgexport-116.png" "Tocorsia Emblem Neroyrika Margrave.png"
mv "svgexport-117.png" "Tocorsia Emblem Monsa County.png"
mv "svgexport-118.png" "Tocorsia Emblem Greseting Margrave.png"
mv "svgexport-119.png" "Tocorsia Emblem Ocieno County.png"
mv "svgexport-120.png" "Tocorsia Emblem Kjelmoenha County.png"
mv "svgexport-121.png" "Tocorsia Emblem Lopsber County.png"
mv "svgexport-122.png" "Tocorsia Emblem Alfsos County.png"
mv "svgexport-123.png" "Tocorsia Emblem Pespo Margrave.png"
mv "svgexport-124.png" "Tocorsia Emblem Aeleagiosia Island.png"
mv "svgexport-125.png" "Tocorsia Emblem Dubkia County.png"
mv "svgexport-126.png" "Tocorsia Emblem Vria Shire.png"
mv "svgexport-127.png" "Tocorsia Emblem Ternozelsk Seneschalty.png"
mv "svgexport-128.png" "Tocorsia Emblem Titin Shire.png"
mv "svgexport-129.png" "Tocorsia Emblem Rshia County.png"
mv "svgexport-130.png" "Tocorsia Emblem Izhok County.png"
mv "svgexport-131.png" "Tocorsia Emblem Bryan County.png"
mv "svgexport-132.png" "Tocorsia Emblem Dubk Seneschalty.png"
mv "svgexport-133.png" "Tocorsia Emblem Vyhov Seneschalty.png"
mv "svgexport-134.png" "Tocorsia Emblem Meres County.png"
mv "svgexport-135.png" "Tocorsia Emblem Pronshe County.png"
mv "svgexport-136.png" "Tocorsia Emblem Bered County.png"
mv "svgexport-137.png" "Tocorsia Emblem Turnikia Territory.png"
mv "svgexport-138.png" "Tocorsia Emblem Aykut Earldom.png"
mv "svgexport-139.png" "Tocorsia Emblem Abemeryurt Earldom.png"
mv "svgexport-140.png" "Tocorsia Emblem Phaisosia County.png"
mv "svgexport-141.png" "Tocorsia Emblem Encszentgia County.png"
mv "svgexport-142.png" "Tocorsia Emblem Fotymarosia County.png"
mv "svgexport-143.png" "Tocorsia Emblem Ablos County.png"
mv "svgexport-144.png" "Tocorsia Emblem Malastarc County.png"
mv "svgexport-145.png" "Tocorsia Emblem Teglas County.png"
mv "svgexport-146.png" "Tocorsia Emblem Theododo County.png"
mv "svgexport-147.png" "Tocorsia Emblem Piraly Landgrave.png"
mv "svgexport-148.png" "Tocorsia Emblem Modunumpe Landgrave.png"
mv "svgexport-149.png" "Tocorsia Emblem Zalintnokia Territory.png"
mv "svgexport-150.png" "Tocorsia Emblem Loinen Earldom.png"
mv "svgexport-151.png" "Tocorsia Emblem Pohtisania County.png"
mv "svgexport-152.png" "Tocorsia Emblem Tulpsa Earldom.png"
mv "svgexport-153.png" "Tocorsia Emblem Bythegia County.png"
mv "svgexport-154.png" "Tocorsia Emblem Ampsamos Shire.png"
mv "svgexport-155.png" "Tocorsia Emblem Crolis Shire.png"
mv "svgexport-156.png" "Tocorsia Emblem Pueblia County.png"
mv "svgexport-157.png" "Tocorsia Emblem Dumia Margrave.png"
mv "svgexport-158.png" "Tocorsia Emblem Milagan County.png"
mv "svgexport-159.png" "Tocorsia Emblem Madrandino County.png"
mv "svgexport-160.png" "Tocorsia Emblem Lutantirue County.png"
mv "svgexport-161.png" "Tocorsia Emblem Nobleras Island.png"
mv "svgexport-162.png" "Tocorsia Emblem Kut County.png"
mv "svgexport-163.png" "Tocorsia Emblem Akarnyurt Margrave.png"
mv "svgexport-164.png" "Tocorsia Emblem Ekinyurt Earldom.png"
mv "svgexport-165.png" "Tocorsia Emblem Baymir County.png"
mv "svgexport-166.png" "Tocorsia Emblem Eniztyurt County.png"
mv "svgexport-167.png" "Tocorsia Emblem Anekereno Earldom.png"
mv "svgexport-168.png" "Tocorsia Emblem Ykut County.png"
mv "svgexport-169.png" "Tocorsia Emblem Keujarvi.png"
mv "svgexport-170.png" "Tocorsia Emblem Kuupina.png"
mv "svgexport-171.png" "Tocorsia Emblem Karnionen.png"
mv "svgexport-172.png" "Tocorsia Emblem Tameskog.png"
mv "svgexport-173.png" "Tocorsia Emblem Onjobyha.png"
mv "svgexport-174.png" "Tocorsia Emblem Esvaavamapa.png"
mv "svgexport-175.png" "Tocorsia Emblem Silkes.png"
mv "svgexport-176.png" "Tocorsia Emblem Prestad.png"
mv "svgexport-177.png" "Tocorsia Emblem Sendovund.png"
mv "svgexport-178.png" "Tocorsia Emblem Soland.png"
mv "svgexport-179.png" "Tocorsia Emblem Myravolen.png"
mv "svgexport-180.png" "Tocorsia Emblem Sosendager.png"
mv "svgexport-181.png" "Tocorsia Emblem Osvolla.png"
mv "svgexport-182.png" "Tocorsia Emblem Valmen.png"
mv "svgexport-183.png" "Tocorsia Emblem Karlva.png"
mv "svgexport-184.png" "Tocorsia Emblem Gopagast.png"
mv "svgexport-185.png" "Tocorsia Emblem Skjerfika.png"
mv "svgexport-186.png" "Tocorsia Emblem Vikholde.png"
mv "svgexport-187.png" "Tocorsia Emblem Ehamnvog.png"
mv "svgexport-188.png" "Tocorsia Emblem Vindeliagus.png"
mv "svgexport-189.png" "Tocorsia Emblem Bakkika.png"
mv "svgexport-190.png" "Tocorsia Emblem Lonstadvog.png"
mv "svgexport-191.png" "Tocorsia Emblem Mehamn.png"
mv "svgexport-192.png" "Tocorsia Emblem Okvikken.png"
mv "svgexport-193.png" "Tocorsia Emblem Hignan.png"
mv "svgexport-194.png" "Tocorsia Emblem Nigripi.png"
mv "svgexport-195.png" "Tocorsia Emblem Sesium.png"
mv "svgexport-196.png" "Tocorsia Emblem Castregul.png"
mv "svgexport-197.png" "Tocorsia Emblem Tauriromulo.png"
mv "svgexport-198.png" "Tocorsia Emblem Ninistium.png"
mv "svgexport-199.png" "Tocorsia Emblem Bonavileven.png"
mv "svgexport-200.png" "Tocorsia Emblem Viltauliob.png"
mv "svgexport-201.png" "Tocorsia Emblem Papinium.png"
mv "svgexport-202.png" "Tocorsia Emblem Pregiovio.png"
mv "svgexport-203.png" "Tocorsia Emblem Theliuscum.png"
mv "svgexport-204.png" "Tocorsia Emblem Besujdus.png"
mv "svgexport-205.png" "Tocorsia Emblem Ketemod.png"
mv "svgexport-206.png" "Tocorsia Emblem Tiskeseny.png"
mv "svgexport-207.png" "Tocorsia Emblem Preruguba.png"
mv "svgexport-208.png" "Tocorsia Emblem Sornum.png"
mv "svgexport-209.png" "Tocorsia Emblem Iganda.png"
mv "svgexport-210.png" "Tocorsia Emblem Roriellen.png"
mv "svgexport-211.png" "Tocorsia Emblem Lugripiro.png"
mv "svgexport-212.png" "Tocorsia Emblem Lincularia.png"
mv "svgexport-213.png" "Tocorsia Emblem Norielum.png"
mv "svgexport-214.png" "Tocorsia Emblem Bonsis.png"
mv "svgexport-215.png" "Tocorsia Emblem Iupigentia.png"
mv "svgexport-216.png" "Tocorsia Emblem Lureticonio.png"
mv "svgexport-217.png" "Tocorsia Emblem Plagus.png"
mv "svgexport-218.png" "Tocorsia Emblem Lesonsis.png"
mv "svgexport-219.png" "Tocorsia Emblem Castra.png"
mv "svgexport-220.png" "Tocorsia Emblem Mantestium.png"
mv "svgexport-221.png" "Tocorsia Emblem Bolina.png"
mv "svgexport-222.png" "Tocorsia Emblem Pacigulum.png"
mv "svgexport-223.png" "Tocorsia Emblem Flabiequm.png"
mv "svgexport-224.png" "Tocorsia Emblem Vicacalebu.png"
mv "svgexport-225.png" "Tocorsia Emblem Callentego.png"
mv "svgexport-226.png" "Tocorsia Emblem Pollum.png"
mv "svgexport-227.png" "Tocorsia Emblem Vegulbiumno.png"
mv "svgexport-228.png" "Tocorsia Emblem Ativium.png"
mv "svgexport-229.png" "Tocorsia Emblem Sirnonia.png"
mv "svgexport-230.png" "Tocorsia Emblem Traterilia.png"
mv "svgexport-231.png" "Tocorsia Emblem Jaszsolca.png"
mv "svgexport-232.png" "Tocorsia Emblem Tus.png"
mv "svgexport-233.png" "Tocorsia Emblem Vaaksyhala.png"
mv "svgexport-234.png" "Tocorsia Emblem Valvi.png"
mv "svgexport-235.png" "Tocorsia Emblem Riila.png"
mv "svgexport-236.png" "Tocorsia Emblem Valga.png"
mv "svgexport-237.png" "Tocorsia Emblem Lokvemi.png"
mv "svgexport-238.png" "Tocorsia Emblem Herton.png"
mv "svgexport-239.png" "Tocorsia Emblem Bjorva.png"
mv "svgexport-240.png" "Tocorsia Emblem Kasjarvinen.png"
mv "svgexport-241.png" "Tocorsia Emblem Bunsey.png"
mv "svgexport-242.png" "Tocorsia Emblem Stanydon.png"
mv "svgexport-243.png" "Tocorsia Emblem Eljana.png"
mv "svgexport-244.png" "Tocorsia Emblem Norinentaue.png"
mv "svgexport-245.png" "Tocorsia Emblem Haapuna.png"
mv "svgexport-246.png" "Tocorsia Emblem Heikemi.png"
mv "svgexport-247.png" "Tocorsia Emblem Numsasali.png"
mv "svgexport-248.png" "Tocorsia Emblem Dmitrognia.png"
mv "svgexport-249.png" "Tocorsia Emblem Hirvi.png"
mv "svgexport-250.png" "Tocorsia Emblem Pohjaki.png"
mv "svgexport-251.png" "Tocorsia Emblem Nenetslavl.png"
mv "svgexport-252.png" "Tocorsia Emblem Denev.png"
mv "svgexport-253.png" "Tocorsia Emblem Shuli.png"
mv "svgexport-254.png" "Tocorsia Emblem Rylsk.png"
mv "svgexport-255.png" "Tocorsia Emblem Viesuutavon.png"
mv "svgexport-256.png" "Tocorsia Emblem Tuukka.png"
mv "svgexport-257.png" "Tocorsia Emblem Redckington.png"
mv "svgexport-258.png" "Tocorsia Emblem Sidmin.png"
mv "svgexport-259.png" "Tocorsia Emblem Porgamepaa.png"
mv "svgexport-260.png" "Tocorsia Emblem Vruchev.png"
mv "svgexport-261.png" "Tocorsia Emblem Huitti.png"
mv "svgexport-262.png" "Tocorsia Emblem Kotsarinen.png"
mv "svgexport-263.png" "Tocorsia Emblem Kuriksalu.png"
mv "svgexport-264.png" "Tocorsia Emblem Hatka.png"
mv "svgexport-265.png" "Tocorsia Emblem Sanikaa.png"
mv "svgexport-266.png" "Tocorsia Emblem Tuukkavesuu.png"
mv "svgexport-267.png" "Tocorsia Emblem Mustti.png"
mv "svgexport-268.png" "Tocorsia Emblem Kalmavon.png"
mv "svgexport-269.png" "Tocorsia Emblem Tioratta.png"
mv "svgexport-270.png" "Tocorsia Emblem Kunvaa.png"
mv "svgexport-271.png" "Tocorsia Emblem Vilpiokos.png"
mv "svgexport-272.png" "Tocorsia Emblem Turnovets.png"
mv "svgexport-273.png" "Tocorsia Emblem Kuupunkote.png"
mv "svgexport-274.png" "Tocorsia Emblem Hirvi.png"
mv "svgexport-275.png" "Tocorsia Emblem Kohttina.png"
mv "svgexport-276.png" "Tocorsia Emblem Hiralisio.png"
mv "svgexport-277.png" "Tocorsia Emblem Gomelno.png"
mv "svgexport-278.png" "Tocorsia Emblem Epepesen.png"
mv "svgexport-279.png" "Tocorsia Emblem Bokuz Oka.png"
mv "svgexport-280.png" "Tocorsia Emblem Aynak.png"
mv "svgexport-281.png" "Tocorsia Emblem Amakayol.png"
mv "svgexport-282.png" "Tocorsia Emblem Yelpozoklu.png"
mv "svgexport-283.png" "Tocorsia Emblem Ayurtopra.png"
mv "svgexport-284.png" "Tocorsia Emblem Sivrek.png"
mv "svgexport-285.png" "Tocorsia Emblem Esonia.png"
mv "svgexport-286.png" "Tocorsia Emblem Geleo.png"
mv "svgexport-287.png" "Tocorsia Emblem Poscataticen.png"
mv "svgexport-288.png" "Tocorsia Emblem Seza.png"
mv "svgexport-289.png" "Tocorsia Emblem Santa.png"
mv "svgexport-290.png" "Tocorsia Emblem Cagosta.png"
mv "svgexport-291.png" "Tocorsia Emblem Sazdeyoba.png"
mv "svgexport-292.png" "Tocorsia Emblem Aya Kay.png"
mv "svgexport-293.png" "Tocorsia Emblem Anocanar.png"
mv "svgexport-294.png" "Tocorsia Emblem Boykutlure.png"
mv "svgexport-295.png" "Tocorsia Emblem Aykorka.png"
mv "svgexport-296.png" "Tocorsia Emblem Kozozobaya.png"
mv "svgexport-297.png" "Tocorsia Emblem Asun.png"
mv "svgexport-298.png" "Tocorsia Emblem Erteli.png"
mv "svgexport-299.png" "Tocorsia Emblem Dobaleren.png"
mv "svgexport-300.png" "Tocorsia Emblem Dolu.png"
mv "svgexport-301.png" "Tocorsia Emblem Denekibi.png"
mv "svgexport-302.png" "Tocorsia Emblem Alte.png"
mv "svgexport-303.png" "Tocorsia Emblem Derenbey.png"
mv "svgexport-304.png" "Tocorsia Emblem Ayraz.png"
mv "svgexport-305.png" "Tocorsia Emblem Bayterepe.png"
mv "svgexport-306.png" "Tocorsia Emblem Sivreli.png"
mv "svgexport-307.png" "Tocorsia Emblem Aldedu.png"
mv "svgexport-308.png" "Tocorsia Emblem Castte.png"
mv "svgexport-309.png" "Tocorsia Emblem Anagnonese.png"
mv "svgexport-310.png" "Tocorsia Emblem Marma.png"
mv "svgexport-311.png" "Tocorsia Emblem Ocayunt.png"
mv "svgexport-312.png" "Tocorsia Emblem Eseribilya.png"
mv "svgexport-313.png" "Tocorsia Emblem Ser Yur.png"
mv "svgexport-314.png" "Tocorsia Emblem Yenyolkan.png"
mv "svgexport-315.png" "Tocorsia Emblem Kopuzbey.png"
mv "svgexport-316.png" "Tocorsia Emblem Amakardi.png"
mv "svgexport-317.png" "Tocorsia Emblem Aslasunkor.png"
mv "svgexport-318.png" "Tocorsia Emblem Atar.png"
mv "svgexport-319.png" "Tocorsia Emblem Sayakarnu.png"
mv "svgexport-320.png" "Tocorsia Emblem Kardepepe.png"
mv "svgexport-321.png" "Tocorsia Emblem Snovsk.png"
mv "svgexport-322.png" "Tocorsia Emblem Kovetstis.png"
mv "svgexport-323.png" "Tocorsia Emblem Cherpeysk.png"
mv "svgexport-324.png" "Tocorsia Emblem Krevolensk.png"
mv "svgexport-325.png" "Tocorsia Emblem Deyatichsk.png"
mv "svgexport-326.png" "Tocorsia Emblem Uryemebo.png"
mv "svgexport-327.png" "Tocorsia Emblem Zubkin.png"
mv "svgexport-328.png" "Tocorsia Emblem Trubchevsk.png"
mv "svgexport-329.png" "Tocorsia Emblem Rombor.png"
mv "svgexport-330.png" "Tocorsia Emblem Nezetsk.png"
mv "svgexport-331.png" "Tocorsia Emblem Rubutsk.png"
mv "svgexport-332.png" "Tocorsia Emblem Vyatrov.png"
mv "svgexport-333.png" "Tocorsia Emblem Krerev.png"
mv "svgexport-334.png" "Tocorsia Emblem Serdere.png"
mv "svgexport-335.png" "Tocorsia Emblem Kursk.png"
mv "svgexport-336.png" "Tocorsia Emblem Svisk.png"
mv "svgexport-337.png" "Tocorsia Emblem Konichesk.png"
mv "svgexport-338.png" "Tocorsia Emblem Klech.png"
mv "svgexport-339.png" "Tocorsia Emblem Luryn.png"
mv "svgexport-340.png" "Tocorsia Emblem Vruch.png"
mv "svgexport-341.png" "Tocorsia Emblem Belno.png"
mv "svgexport-342.png" "Tocorsia Emblem Beiras.png"
mv "svgexport-343.png" "Tocorsia Emblem Relar.png"
mv "svgexport-344.png" "Tocorsia Emblem Alhao.png"
mv "svgexport-345.png" "Tocorsia Emblem Maril.png"
mv "svgexport-346.png" "Tocorsia Emblem Porvelas.png"
mv "svgexport-347.png" "Tocorsia Emblem Silhos.png"
mv "svgexport-348.png" "Tocorsia Emblem Cartava.png"
mv "svgexport-349.png" "Tocorsia Emblem Barteixeiro.png"
mv "svgexport-350.png" "Tocorsia Emblem Vorod.png"
mv "svgexport-351.png" "Tocorsia Emblem Ponho.png"
mv "svgexport-352.png" "Tocorsia Emblem Abralmeiras.png"
mv "svgexport-353.png" "Tocorsia Emblem Eueimapinha.png"
mv "svgexport-354.png" "Tocorsia Emblem Lueiracacao.png"
mv "svgexport-355.png" "Tocorsia Emblem Milvoso.png"
mv "svgexport-356.png" "Tocorsia Emblem Ildoareza.png"
mv "svgexport-357.png" "Tocorsia Emblem Horod.png"
mv "svgexport-358.png" "Tocorsia Emblem Belzhech.png"
mv "svgexport-359.png" "Tocorsia Emblem Seinas.png"
mv "svgexport-360.png" "Tocorsia Emblem Zhilov.png"
mv "svgexport-361.png" "Tocorsia Emblem Chetebovl.png"
mv "svgexport-362.png" "Tocorsia Emblem Chechers.png"
mv "svgexport-363.png" "Tocorsia Emblem Cherlets.png"
mv "svgexport-364.png" "Tocorsia Emblem Turnatin.png"
mv "svgexport-365.png" "Tocorsia Emblem Kovoresk.png"
mv "svgexport-366.png" "Tocorsia Emblem Tersun.png"
mv "svgexport-367.png" "Tocorsia Emblem Velecha.png"
mv "svgexport-368.png" "Tocorsia Emblem Krylatsk.png"
mv "svgexport-369.png" "Tocorsia Emblem Zizhetshon.png"
mv "svgexport-370.png" "Tocorsia Emblem Drutslavl.png"
mv "svgexport-371.png" "Tocorsia Emblem Nympsos.png"
mv "svgexport-372.png" "Tocorsia Emblem Naupia.png"
mv "svgexport-373.png" "Tocorsia Emblem Bometos.png"
mv "svgexport-374.png" "Tocorsia Emblem Bhrylos.png"
mv "svgexport-375.png" "Tocorsia Emblem Gypeiaros.png"
mv "svgexport-376.png" "Tocorsia Emblem Taubeaca.png"
mv "svgexport-377.png" "Tocorsia Emblem Lalorion.png"
mv "svgexport-378.png" "Tocorsia Emblem Gournia.png"
mv "svgexport-379.png" "Tocorsia Emblem Sanos.png"
mv "svgexport-380.png" "Tocorsia Emblem Kimnos.png"
mv "svgexport-381.png" "Tocorsia Emblem Taura.png"
mv "svgexport-382.png" "Tocorsia Emblem Thaphizi.png"
mv "svgexport-383.png" "Tocorsia Emblem Seceramis.png"
mv "svgexport-384.png" "Tocorsia Emblem Histhos.png"
mv "svgexport-385.png" "Tocorsia Emblem Pithos.png"
mv "svgexport-386.png" "Tocorsia Emblem Acharganais.png"
mv "svgexport-387.png" "Tocorsia Emblem Exandna.png"
mv "svgexport-388.png" "Tocorsia Emblem Akynthi.png"
mv "svgexport-389.png" "Tocorsia Emblem Castigliaro.png"
mv "svgexport-390.png" "Tocorsia Emblem Campiviniano.png"
mv "svgexport-391.png" "Tocorsia Emblem Piglianonere.png"
mv "svgexport-392.png" "Tocorsia Emblem Petrovia.png"
mv "svgexport-393.png" "Tocorsia Emblem Eschbrin.png"
mv "svgexport-394.png" "Tocorsia Emblem Durzell.png"
mv "svgexport-395.png" "Tocorsia Emblem Alrotig.png"
mv "svgexport-396.png" "Tocorsia Emblem Mahllingen.png"
mv "svgexport-397.png" "Tocorsia Emblem Kapen.png"
mv "svgexport-398.png" "Tocorsia Emblem Ropovensk.png"
mv "svgexport-399.png" "Tocorsia Emblem Kapeden.png"
mv "svgexport-400.png" "Tocorsia Emblem Todttingen.png"
mv "svgexport-401.png" "Tocorsia Emblem Frohn.png"
mv "svgexport-402.png" "Tocorsia Emblem Donausach.png"
mv "svgexport-403.png" "Tocorsia Emblem Bollsbach.png"
mv "svgexport-404.png" "Tocorsia Emblem Ohlsfeld.png"
mv "svgexport-405.png" "Tocorsia Emblem Kirchal.png"
mv "svgexport-406.png" "Tocorsia Emblem Weilburg.png"
mv "svgexport-407.png" "Tocorsia Emblem Siminburg.png"
mv "svgexport-408.png" "Tocorsia Emblem Hofswefenb.png"
mv "svgexport-409.png" "Tocorsia Emblem Furttengen.png"
mv "svgexport-410.png" "Tocorsia Emblem Hutertal.png"
mv "svgexport-411.png" "Tocorsia Emblem Hertenheim.png"
mv "svgexport-412.png" "Tocorsia Emblem Stauberg.png"
mv "svgexport-413.png" "Tocorsia Emblem Ballingen.png"
mv "svgexport-414.png" "Tocorsia Emblem Ellinheim.png"
mv "svgexport-415.png" "Tocorsia Emblem Kapbach.png"
mv "svgexport-416.png" "Tocorsia Emblem Rheisenau.png"
mv "svgexport-417.png" "Tocorsia Emblem Furttersteig.png"
mv "svgexport-418.png" "Tocorsia Emblem Braunzelngen.png"
mv "svgexport-419.png" "Tocorsia Emblem Frebenin.png"
mv "svgexport-420.png" "Tocorsia Emblem Sasheimin.png"
mv "svgexport-421.png" "Tocorsia Emblem Nordt.png"
mv "svgexport-422.png" "Tocorsia Emblem Sastadtnau.png"
mv "svgexport-423.png" "Tocorsia Emblem Harken.png"
mv "svgexport-424.png" "Tocorsia Emblem Schopenberg.png"
mv "svgexport-425.png" "Tocorsia Emblem Frohngengen.png"
mv "svgexport-426.png" "Tocorsia Emblem Kapeier.png"
mv "svgexport-427.png" "Tocorsia Emblem Onauninzeln.png"
mv "svgexport-428.png" "Tocorsia Emblem Mordo.png"
mv "svgexport-429.png" "Tocorsia Emblem Segni.png"
mv "svgexport-430.png" "Tocorsia Emblem Marcellela.png"
mv "svgexport-431.png" "Tocorsia Emblem Trino.png"
mv "svgexport-432.png" "Tocorsia Emblem Castelliter.png"
mv "svgexport-433.png" "Tocorsia Emblem Posta.png"
mv "svgexport-434.png" "Tocorsia Emblem Samba.png"
mv "svgexport-435.png" "Tocorsia Emblem Rolinia.png"
mv "svgexport-436.png" "Tocorsia Emblem Ebron.png"
mv "svgexport-437.png" "Tocorsia Emblem Buhweisingen.png"
mv "svgexport-438.png" "Tocorsia Emblem Zauernheim.png"
mv "svgexport-439.png" "Tocorsia Emblem Sulzgraden.png"
mv "svgexport-440.png" "Tocorsia Emblem Lauch.png"
mv "svgexport-441.png" "Tocorsia Emblem Lahrheim.png"
mv "svgexport-442.png" "Tocorsia Emblem Donaufenbach.png"
mv "svgexport-443.png" "Tocorsia Emblem Iterken.png"
mv "svgexport-444.png" "Tocorsia Emblem Durnach.png"
mv "svgexport-445.png" "Tocorsia Emblem Oreden.png"
mv "svgexport-446.png" "Tocorsia Emblem Rhein.png"
mv "svgexport-447.png" "Tocorsia Emblem Einengenmuns.png"
mv "svgexport-448.png" "Tocorsia Emblem Avetera.png"
mv "svgexport-449.png" "Tocorsia Emblem Nuzondejos.png"
mv "svgexport-450.png" "Tocorsia Emblem Alares.png"
mv "svgexport-451.png" "Tocorsia Emblem Yunca.png"
mv "svgexport-452.png" "Tocorsia Emblem Cantius.png"
mv "svgexport-453.png" "Tocorsia Emblem Sandilluman.png"
mv "svgexport-454.png" "Tocorsia Emblem Luquegoso.png"
mv "svgexport-455.png" "Tocorsia Emblem Sallorana.png"
mv "svgexport-456.png" "Tocorsia Emblem Senaresala.png"
mv "svgexport-457.png" "Tocorsia Emblem Sejondo.png"
mv "svgexport-458.png" "Tocorsia Emblem Gorgan.png"
mv "svgexport-459.png" "Tocorsia Emblem Nesmos.png"
mv "svgexport-460.png" "Tocorsia Emblem Aeracra.png"
mv "svgexport-461.png" "Tocorsia Emblem Talia.png"
mv "svgexport-462.png" "Tocorsia Emblem Citri.png"
mv "svgexport-463.png" "Tocorsia Emblem Vimonterano.png"
mv "svgexport-464.png" "Tocorsia Emblem Configliano.png"
mv "svgexport-465.png" "Tocorsia Emblem Ronzio.png"
mv "svgexport-466.png" "Tocorsia Emblem Castello.png"
mv "svgexport-467.png" "Tocorsia Emblem Valvicerelvi.png"
mv "svgexport-468.png" "Tocorsia Emblem Vallucino.png"
mv "svgexport-469.png" "Tocorsia Emblem Rioflavigna.png"
mv "svgexport-470.png" "Tocorsia Emblem Guinovonene.png"
mv "svgexport-471.png" "Tocorsia Emblem Trevari.png"
mv "svgexport-472.png" "Tocorsia Emblem Tollo.png"
mv "svgexport-473.png" "Tocorsia Emblem Nespeno.png"
mv "svgexport-474.png" "Tocorsia Emblem Fornolinone.png"
mv "svgexport-475.png" "Tocorsia Emblem Abros.png"
mv "svgexport-476.png" "Tocorsia Emblem Herondos.png"
mv "svgexport-477.png" "Tocorsia Emblem Tempia.png"
mv "svgexport-478.png" "Tocorsia Emblem Tronaion.png"
mv "svgexport-479.png" "Tocorsia Emblem Lenesia.png"
mv "svgexport-480.png" "Tocorsia Emblem Anera.png"
mv "svgexport-481.png" "Tocorsia Emblem Ineleuthe.png"
mv "svgexport-482.png" "Tocorsia Emblem Hyeta.png"
mv "svgexport-483.png" "Tocorsia Emblem Grottero.png"
mv "svgexport-484.png" "Tocorsia Emblem Belletaricca.png"
mv "svgexport-485.png" "Tocorsia Emblem Iarathory.png"
mv "svgexport-486.png" "Tocorsia Emblem Phatossa.png"
mv "svgexport-487.png" "Tocorsia Emblem Sipolis.png"
mv "svgexport-488.png" "Tocorsia Emblem Stymphidam.png"
mv "svgexport-489.png" "Tocorsia Emblem Netrinonema.png"
mv "svgexport-490.png" "Tocorsia Emblem Caprano.png"
mv "svgexport-491.png" "Tocorsia Emblem Posiano.png"
mv "svgexport-492.png" "Tocorsia Emblem Farvianoro.png"
mv "svgexport-493.png" "Tocorsia Emblem Broccalatra.png"
mv "svgexport-494.png" "Tocorsia Emblem Citrasecqua.png"
mv "svgexport-495.png" "Tocorsia Emblem Tuspeta.png"
mv "svgexport-496.png" "Tocorsia Emblem Sernolimoni.png"
mv "svgexport-497.png" "Tocorsia Emblem Piniano.png"
mv "svgexport-498.png" "Tocorsia Emblem Lenene.png"
mv "svgexport-499.png" "Tocorsia Emblem Dalfos.png"
mv "svgexport-500.png" "Tocorsia Emblem Rokurna.png"
mv "svgexport-501.png" "Tocorsia Emblem Skrogavoya.png"
mv "svgexport-502.png" "Tocorsia Emblem Vopeidger.png"
mv "svgexport-503.png" "Tocorsia Emblem Laudark.png"
mv "svgexport-504.png" "Tocorsia Emblem Oklausta.png"
mv "svgexport-505.png" "Tocorsia Emblem Silder.png"
mv "svgexport-506.png" "Tocorsia Emblem Supipiniafer.png"
mv "svgexport-507.png" "Tocorsia Emblem Leramignica.png"
mv "svgexport-508.png" "Tocorsia Emblem Giupo.png"
mv "svgexport-509.png" "Tocorsia Emblem Hopastad.png"
mv "svgexport-510.png" "Tocorsia Emblem Sorneske.png"
mv "svgexport-511.png" "Tocorsia Emblem Blokka.png"
mv "svgexport-512.png" "Tocorsia Emblem Jarnstalur.png"
mv "svgexport-513.png" "Tocorsia Emblem Reisafting.png"
mv "svgexport-514.png" "Tocorsia Emblem Neroyrika.png"
mv "svgexport-515.png" "Tocorsia Emblem Vevermah.png"
mv "svgexport-516.png" "Tocorsia Emblem Garnesvik.png"
mv "svgexport-517.png" "Tocorsia Emblem Monsa.png"
mv "svgexport-518.png" "Tocorsia Emblem Ponte.png"
mv "svgexport-519.png" "Tocorsia Emblem Colle.png"
mv "svgexport-520.png" "Tocorsia Emblem Monza.png"
mv "svgexport-521.png" "Tocorsia Emblem Tjardurdur.png"
mv "svgexport-522.png" "Tocorsia Emblem Greseting.png"
mv "svgexport-523.png" "Tocorsia Emblem Kovina.png"
mv "svgexport-524.png" "Tocorsia Emblem Seldalva.png"
mv "svgexport-525.png" "Tocorsia Emblem Buroyrika.png"
mv "svgexport-526.png" "Tocorsia Emblem Flaksvik.png"
mv "svgexport-527.png" "Tocorsia Emblem Fjerka.png"
mv "svgexport-528.png" "Tocorsia Emblem Hvangaber.png"
mv "svgexport-529.png" "Tocorsia Emblem Conicono.png"
mv "svgexport-530.png" "Tocorsia Emblem Cadiscorocch.png"
mv "svgexport-531.png" "Tocorsia Emblem Sella.png"
mv "svgexport-532.png" "Tocorsia Emblem Norbo.png"
mv "svgexport-533.png" "Tocorsia Emblem Price.png"
mv "svgexport-534.png" "Tocorsia Emblem Normaco.png"
mv "svgexport-535.png" "Tocorsia Emblem Ocieno.png"
mv "svgexport-536.png" "Tocorsia Emblem Neleo.png"
mv "svgexport-537.png" "Tocorsia Emblem Vicevi.png"
mv "svgexport-538.png" "Tocorsia Emblem Castro.png"
mv "svgexport-539.png" "Tocorsia Emblem Sorfika.png"
mv "svgexport-540.png" "Tocorsia Emblem Kjelmoenha.png"
mv "svgexport-541.png" "Tocorsia Emblem Hnifsfells.png"
mv "svgexport-542.png" "Tocorsia Emblem Lopsber.png"
mv "svgexport-543.png" "Tocorsia Emblem Gladsvi.png"
mv "svgexport-544.png" "Tocorsia Emblem Hautover.png"
mv "svgexport-545.png" "Tocorsia Emblem Greloyri.png"
mv "svgexport-546.png" "Tocorsia Emblem Riofradubia.png"
mv "svgexport-547.png" "Tocorsia Emblem Seglia.png"
mv "svgexport-548.png" "Tocorsia Emblem Pespo.png"
mv "svgexport-549.png" "Tocorsia Emblem Montanicara.png"
mv "svgexport-550.png" "Tocorsia Emblem Dorogoga.png"
mv "svgexport-551.png" "Tocorsia Emblem Morobesk.png"
mv "svgexport-552.png" "Tocorsia Emblem Molensk.png"
mv "svgexport-553.png" "Tocorsia Emblem Luchinoro.png"
mv "svgexport-554.png" "Tocorsia Emblem Morogosk.png"
mv "svgexport-555.png" "Tocorsia Emblem Krichvost.png"
mv "svgexport-556.png" "Tocorsia Emblem Ternozelsk.png"
mv "svgexport-557.png" "Tocorsia Emblem Sizhersla.png"
mv "svgexport-558.png" "Tocorsia Emblem Streshon.png"
mv "svgexport-559.png" "Tocorsia Emblem Drestrov.png"
mv "svgexport-560.png" "Tocorsia Emblem Titin.png"
mv "svgexport-561.png" "Tocorsia Emblem Herwihlpirs.png"
mv "svgexport-562.png" "Tocorsia Emblem Temyshl.png"
mv "svgexport-563.png" "Tocorsia Emblem Gororochu.png"
mv "svgexport-564.png" "Tocorsia Emblem Chelug.png"
mv "svgexport-565.png" "Tocorsia Emblem Verere.png"
mv "svgexport-566.png" "Tocorsia Emblem Leretsk.png"
mv "svgexport-567.png" "Tocorsia Emblem Mozelsk.png"
mv "svgexport-568.png" "Tocorsia Emblem Rzhisk.png"
mv "svgexport-569.png" "Tocorsia Emblem Roslav.png"
mv "svgexport-570.png" "Tocorsia Emblem Ostsa.png"
mv "svgexport-571.png" "Tocorsia Emblem Dopolch.png"
mv "svgexport-572.png" "Tocorsia Emblem Mosch.png"
mv "svgexport-573.png" "Tocorsia Emblem Zvereres.png"
mv "svgexport-574.png" "Tocorsia Emblem Goroginy.png"
mv "svgexport-575.png" "Tocorsia Emblem Cherlen.png"
mv "svgexport-576.png" "Tocorsia Emblem Zubkiza.png"
mv "svgexport-577.png" "Tocorsia Emblem Perez.png"
mv "svgexport-578.png" "Tocorsia Emblem Bryan.png"
mv "svgexport-579.png" "Tocorsia Emblem Pinsk.png"
mv "svgexport-580.png" "Tocorsia Emblem Sochenets.png"
mv "svgexport-581.png" "Tocorsia Emblem Vyhov.png"
mv "svgexport-582.png" "Tocorsia Emblem Socheyask.png"
mv "svgexport-583.png" "Tocorsia Emblem Vomel.png"
mv "svgexport-584.png" "Tocorsia Emblem Nemenets.png"
mv "svgexport-585.png" "Tocorsia Emblem Zubechiy.png"
mv "svgexport-586.png" "Tocorsia Emblem Subechi.png"
mv "svgexport-587.png" "Tocorsia Emblem Pororokoe.png"
mv "svgexport-588.png" "Tocorsia Emblem Meres.png"
mv "svgexport-589.png" "Tocorsia Emblem Serna.png"
mv "svgexport-590.png" "Tocorsia Emblem Hotrog.png"
mv "svgexport-591.png" "Tocorsia Emblem Klechkin.png"
mv "svgexport-592.png" "Tocorsia Emblem Orodubkov.png"
mv "svgexport-593.png" "Tocorsia Emblem Pronshe.png"
mv "svgexport-594.png" "Tocorsia Emblem Svisk.png"
mv "svgexport-595.png" "Tocorsia Emblem Odisch.png"
mv "svgexport-596.png" "Tocorsia Emblem Lolichito.png"
mv "svgexport-597.png" "Tocorsia Emblem Bodischka.png"
mv "svgexport-598.png" "Tocorsia Emblem Gorogotin.png"
mv "svgexport-599.png" "Tocorsia Emblem Korod.png"
mv "svgexport-600.png" "Tocorsia Emblem Aykut.png"
mv "svgexport-601.png" "Tocorsia Emblem Boyuzun.png"
mv "svgexport-602.png" "Tocorsia Emblem Yazsumanka.png"
mv "svgexport-603.png" "Tocorsia Emblem Aykut.png"
mv "svgexport-604.png" "Tocorsia Emblem Top Tekepe.png"
mv "svgexport-605.png" "Tocorsia Emblem Yolkanbey.png"
mv "svgexport-606.png" "Tocorsia Emblem Tydolis.png"
mv "svgexport-607.png" "Tocorsia Emblem Marna.png"
mv "svgexport-608.png" "Tocorsia Emblem Ampliossos.png"
mv "svgexport-609.png" "Tocorsia Emblem Akrolis.png"
mv "svgexport-610.png" "Tocorsia Emblem Einalur.png"
mv "svgexport-611.png" "Tocorsia Emblem Vadadi.png"
mv "svgexport-612.png" "Tocorsia Emblem Szamazlonalma.png"
mv "svgexport-613.png" "Tocorsia Emblem Zadorinckeny.png"
mv "svgexport-614.png" "Tocorsia Emblem Szagyver.png"
mv "svgexport-615.png" "Tocorsia Emblem Keleklosvovar.png"
mv "svgexport-616.png" "Tocorsia Emblem Zakrotige.png"
mv "svgexport-617.png" "Tocorsia Emblem Ablos.png"
mv "svgexport-618.png" "Tocorsia Emblem Izfegy.png"
mv "svgexport-619.png" "Tocorsia Emblem Nalombat.png"
mv "svgexport-620.png" "Tocorsia Emblem Tiszalavecses.png"
mv "svgexport-621.png" "Tocorsia Emblem Fudoroksle.png"
mv "svgexport-622.png" "Tocorsia Emblem Sardony.png"
mv "svgexport-623.png" "Tocorsia Emblem Dombrad.png"
mv "svgexport-624.png" "Tocorsia Emblem Femecseszaver.png"
mv "svgexport-625.png" "Tocorsia Emblem Szanosteher.png"
mv "svgexport-626.png" "Tocorsia Emblem Teglas.png"
mv "svgexport-627.png" "Tocorsia Emblem Podosiaralo.png"
mv "svgexport-628.png" "Tocorsia Emblem Corgan.png"
mv "svgexport-629.png" "Tocorsia Emblem Akroi.png"
mv "svgexport-630.png" "Tocorsia Emblem Crolis.png"
mv "svgexport-631.png" "Tocorsia Emblem Braukeiala.png"
mv "svgexport-632.png" "Tocorsia Emblem Malorant.png"
mv "svgexport-633.png" "Tocorsia Emblem Zsambeklad.png"
mv "svgexport-634.png" "Tocorsia Emblem Pyrgan.png"
mv "svgexport-635.png" "Tocorsia Emblem Piraly.png"
mv "svgexport-636.png" "Tocorsia Emblem Throlissa.png"
mv "svgexport-637.png" "Tocorsia Emblem Morgoscu.png"
mv "svgexport-638.png" "Tocorsia Emblem Rareagus.png"
mv "svgexport-639.png" "Tocorsia Emblem Modunumpe.png"
mv "svgexport-640.png" "Tocorsia Emblem Sirmium.png"
mv "svgexport-641.png" "Tocorsia Emblem Tonytely.png"
mv "svgexport-642.png" "Tocorsia Emblem Loinen.png"
mv "svgexport-643.png" "Tocorsia Emblem Palari.png"
mv "svgexport-644.png" "Tocorsia Emblem Benpaa.png"
mv "svgexport-645.png" "Tocorsia Emblem Miikaulasa.png"
mv "svgexport-646.png" "Tocorsia Emblem Pioltti.png"
mv "svgexport-647.png" "Tocorsia Emblem Tuuska.png"
mv "svgexport-648.png" "Tocorsia Emblem Huitsaueva.png"
mv "svgexport-649.png" "Tocorsia Emblem Tulpsa.png"
mv "svgexport-650.png" "Tocorsia Emblem Perttumamo.png"
mv "svgexport-651.png" "Tocorsia Emblem Hera.png"
mv "svgexport-652.png" "Tocorsia Emblem Nympliosme.png"
mv "svgexport-653.png" "Tocorsia Emblem Ampsamos.png"
mv "svgexport-654.png" "Tocorsia Emblem Marga.png"
mv "svgexport-655.png" "Tocorsia Emblem Anos.png"
mv "svgexport-656.png" "Tocorsia Emblem Meleuraris.png"
mv "svgexport-657.png" "Tocorsia Emblem Aklesmos.png"
mv "svgexport-658.png" "Tocorsia Emblem Aktos.png"
mv "svgexport-659.png" "Tocorsia Emblem Crolis.png"
mv "svgexport-660.png" "Tocorsia Emblem Gourniala.png"
mv "svgexport-661.png" "Tocorsia Emblem Rhamnos.png"
mv "svgexport-662.png" "Tocorsia Emblem Piba.png"
mv "svgexport-663.png" "Tocorsia Emblem Porea.png"
mv "svgexport-664.png" "Tocorsia Emblem Jiruesevosa.png"
mv "svgexport-665.png" "Tocorsia Emblem Illes.png"
mv "svgexport-666.png" "Tocorsia Emblem Zircserdorok.png"
mv "svgexport-667.png" "Tocorsia Emblem Albenzonda.png"
mv "svgexport-668.png" "Tocorsia Emblem Milviscozas.png"
mv "svgexport-669.png" "Tocorsia Emblem Pinos.png"
mv "svgexport-670.png" "Tocorsia Emblem Tosoce.png"
mv "svgexport-671.png" "Tocorsia Emblem Lunozas.png"
mv "svgexport-672.png" "Tocorsia Emblem Marbomaros.png"
mv "svgexport-673.png" "Tocorsia Emblem Torgejos.png"
mv "svgexport-674.png" "Tocorsia Emblem Totos.png"
mv "svgexport-675.png" "Tocorsia Emblem Konymahagyec.png"
mv "svgexport-676.png" "Tocorsia Emblem Puszsolgarhi.png"
mv "svgexport-677.png" "Tocorsia Emblem Madrandino.png"
mv "svgexport-678.png" "Tocorsia Emblem Torgos.png"
mv "svgexport-679.png" "Tocorsia Emblem Lutantirue.png"
mv "svgexport-680.png" "Tocorsia Emblem Mihuecilfor.png"
mv "svgexport-681.png" "Tocorsia Emblem Sauzaquevo.png"
mv "svgexport-682.png" "Tocorsia Emblem Tembla.png"
mv "svgexport-683.png" "Tocorsia Emblem Kut.png"
mv "svgexport-684.png" "Tocorsia Emblem Boyayteri.png"
mv "svgexport-685.png" "Tocorsia Emblem Dekepepeki.png"
mv "svgexport-686.png" "Tocorsia Emblem Balkan.png"
mv "svgexport-687.png" "Tocorsia Emblem Ayazyaneno.png"
mv "svgexport-688.png" "Tocorsia Emblem Bozkalazte.png"
mv "svgexport-689.png" "Tocorsia Emblem Top Ok.png"
mv "svgexport-690.png" "Tocorsia Emblem Yelpova.png"
mv "svgexport-691.png" "Tocorsia Emblem Erilekesen.png"
mv "svgexport-692.png" "Tocorsia Emblem Kodurcibey.png"
mv "svgexport-693.png" "Tocorsia Emblem Ganarnu.png"
mv "svgexport-694.png" "Tocorsia Emblem Dozozopuz.png"
mv "svgexport-695.png" "Tocorsia Emblem Turkaka.png"
mv "svgexport-696.png" "Tocorsia Emblem Aslamalur.png"
mv "svgexport-697.png" "Tocorsia Emblem Hosta.png"
mv "svgexport-698.png" "Tocorsia Emblem Ayli.png"
mv "svgexport-699.png" "Tocorsia Emblem Snovs.png"
mv "svgexport-700.png" "Tocorsia Emblem Mosalsk.png"
mv "svgexport-701.png" "Tocorsia Emblem Ulduluoguz.png"
mv "svgexport-702.png" "Tocorsia Emblem Heisiolina.png"
mv "svgexport-703.png" "Tocorsia Emblem Cedi.png"
mv "svgexport-704.png" "Tocorsia Emblem Klovski.png"
mv "svgexport-705.png" "Tocorsia Emblem Kocanobaka.png"
mv "svgexport-706.png" "Tocorsia Emblem Askaynuz.png"
mv "svgexport-707.png" "Tocorsia Emblem Anekereno.png"
mv "svgexport-708.png" "Tocorsia Emblem Balkan.png"
mv "svgexport-709.png" "Tocorsia Emblem Ykut.png"
mv "svgexport-710.png" "Tocorsia Emblem Ulalahardu.png"